/********************************************************************************
** Form generated from reading UI file 'webcamUI.ui'
**
** Created: Thu 29. May 14:28:01 2014
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WEBCAMUI_H
#define UI_WEBCAMUI_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QScrollBar>
#include <QtGui/QSlider>
#include <QtGui/QStatusBar>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>
#include "../QtCVOverlayWidget/CvOverlayWidget.h"
#include "../QtCvImageWidget/cvimagewidget.h"

QT_BEGIN_NAMESPACE

class Ui_webcamUI
{
public:
    QAction *actionWtf;
    QAction *actionPreload;
    QAction *actionPrint;
    QAction *actionEmail;
    QAction *groundTruth;
    QWidget *centralWidget;
    CvImageWidget *videoWidget;
    QLabel *label_Webcam;
    CvImageWidget *videoWidget_Minioverlay;
    CvImageWidget *videoWidget_Interactive;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_5;
    QLabel *label_Interactive;
    QFrame *line_8;
    QRadioButton *classFourButton;
    QRadioButton *classThreeButton;
    QRadioButton *classOneButton;
    QRadioButton *classTwoButton;
    QPushButton *pushButton_Capture;
    QPushButton *pushButton_SaveClassifier;
    QPushButton *pushButton_LoadClassifer;
    QPushButton *pushButton_StillImage;
    QPushButton *pushButton_TrainClassifer;
    QPushButton *pushButton_Classify;
    QRadioButton *classFiveButton;
    QRadioButton *classSixButton;
    QPushButton *pushButton_ResetBackground;
    QLabel *label_TrainingData;
    QLabel *label_TrainingClass;
    QLabel *label_AmountSelected;
    QFrame *line_23;
    QFrame *line_24;
    QLabel *label_ClassifiedData;
    QFrame *line_25;
    QLabel *label_AmountClassified;
    QFrame *line_26;
    QLabel *label_ClassifiedClass;
    QFrame *line_27;
    QLabel *label_ClassifiedPercentage;
    CvOverlayWidget *overlayWidget_Minioverlay;
    QPushButton *pushButton_Previous;
    QPushButton *pushButton_Next;
    QPushButton *pushButton_SaveStillImage;
    QLabel *label_PotatoCount;
    QFrame *line_14;
    QFrame *line_9;
    QFrame *line_10;
    QLabel *label_Webcam_2;
    QSlider *thresholdSlider;
    QLabel *label;
    QLabel *label_2;
    QSlider *horizontalSlider;
    QLabel *label_ThresholdValue;
    QLabel *label_AreaValue;
    QScrollBar *hScroll;
    QScrollBar *vScroll;
    QSlider *zoomSlider;
    QLabel *statusLabel;
    CvOverlayWidget *overlayWidget;
    QLabel *label_3;
    QLabel *zoomLabel;
    QLabel *label_5;
    QLabel *label_6;
    QLineEdit *EditClass1;
    QLineEdit *EditClass2;
    QLineEdit *EditClass3;
    QLineEdit *EditClass4;
    QLineEdit *EditClass5;
    QLineEdit *EditClass6;
    QPushButton *pushButton_Edit;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_3;
    QLabel *lblClass1_2;
    QLabel *lblClass2_2;
    QLabel *lblClass3_2;
    QLabel *lblClass4_2;
    QLabel *lblClass5_2;
    QLabel *lblClass6_2;
    QWidget *layoutWidget1;
    QVBoxLayout *verticalLayout_2;
    QLabel *label_SelectedOneVal;
    QLabel *label_SelectedTwoVal;
    QLabel *label_SelectedThreeVal;
    QLabel *label_SelectedFourVal;
    QLabel *label_SelectedFiveVal;
    QLabel *label_SelectedSixVal;
    QWidget *layoutWidget2;
    QVBoxLayout *verticalLayout;
    QLabel *lblClass1;
    QLabel *lblClass2;
    QLabel *lblClass3;
    QLabel *lblClass4;
    QLabel *lblClass5;
    QLabel *lblClass6;
    QWidget *layoutWidget3;
    QVBoxLayout *verticalLayout_4;
    QLabel *label_ClassifiedOneVal;
    QLabel *label_ClassifiedTwoVal;
    QLabel *label_ClassifiedThreeVal;
    QLabel *label_ClassifiedFourVal;
    QLabel *label_ClassifiedFiveVal;
    QLabel *label_ClassifiedSixVal;
    QWidget *layoutWidget4;
    QVBoxLayout *verticalLayout_5;
    QLabel *label_ClassifiedOnePer;
    QLabel *label_ClassifiedTwoPer;
    QLabel *label_ClassifiedThreePer;
    QLabel *label_ClassifiedFourPer;
    QLabel *label_ClassifiedFivePer;
    QLabel *label_ClassifiedSixPer;
    QWidget *layoutWidget_2;
    QVBoxLayout *verticalLayout_7;
    QLabel *lblColClass_1_2;
    QLabel *lblColClass_2_2;
    QLabel *lblColClass_3_2;
    QLabel *lblColClass_4_2;
    QLabel *lblColClass_5_2;
    QLabel *lblColClass_6_2;
    QWidget *layoutWidget5;
    QVBoxLayout *verticalLayout_6;
    QLabel *lblColClass_1;
    QLabel *lblColClass_2;
    QLabel *lblColClass_3;
    QLabel *lblColClass_4;
    QLabel *lblColClass_5;
    QLabel *lblColClass_6;
    QCheckBox *chk_LogImgs;
    QLineEdit *txtLogPrefix;
    QLabel *label_4;
    QLineEdit *txtLogFolder;
    QLabel *label_7;
    QPushButton *btnLogFolder;
    QPushButton *btnLog;
    QFrame *line_11;
    QPushButton *btnOpenFolder;
    QLineEdit *txtLogDesc;
    QPushButton *pushButton_TrainClassifer_2;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *webcamUI)
    {
        if (webcamUI->objectName().isEmpty())
            webcamUI->setObjectName(QString::fromUtf8("webcamUI"));
        webcamUI->resize(1915, 1006);
        actionWtf = new QAction(webcamUI);
        actionWtf->setObjectName(QString::fromUtf8("actionWtf"));
        actionPreload = new QAction(webcamUI);
        actionPreload->setObjectName(QString::fromUtf8("actionPreload"));
        actionPrint = new QAction(webcamUI);
        actionPrint->setObjectName(QString::fromUtf8("actionPrint"));
        actionEmail = new QAction(webcamUI);
        actionEmail->setObjectName(QString::fromUtf8("actionEmail"));
        groundTruth = new QAction(webcamUI);
        groundTruth->setObjectName(QString::fromUtf8("groundTruth"));
        centralWidget = new QWidget(webcamUI);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        videoWidget = new CvImageWidget(centralWidget);
        videoWidget->setObjectName(QString::fromUtf8("videoWidget"));
        videoWidget->setGeometry(QRect(10, 30, 576, 324));
        label_Webcam = new QLabel(centralWidget);
        label_Webcam->setObjectName(QString::fromUtf8("label_Webcam"));
        label_Webcam->setGeometry(QRect(10, 10, 71, 16));
        videoWidget_Minioverlay = new CvImageWidget(centralWidget);
        videoWidget_Minioverlay->setObjectName(QString::fromUtf8("videoWidget_Minioverlay"));
        videoWidget_Minioverlay->setGeometry(QRect(10, 420, 576, 324));
        videoWidget_Interactive = new CvImageWidget(centralWidget);
        videoWidget_Interactive->setObjectName(QString::fromUtf8("videoWidget_Interactive"));
        videoWidget_Interactive->setGeometry(QRect(610, 30, 1280, 720));
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(590, 10, 20, 801));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(10, 810, 1901, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(-1, 390, 600, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(0, 0, 1901, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_Interactive = new QLabel(centralWidget);
        label_Interactive->setObjectName(QString::fromUtf8("label_Interactive"));
        label_Interactive->setGeometry(QRect(615, 10, 101, 16));
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(223, 822, 20, 161));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        classFourButton = new QRadioButton(centralWidget);
        classFourButton->setObjectName(QString::fromUtf8("classFourButton"));
        classFourButton->setGeometry(QRect(730, 790, 16, 17));
        classFourButton->setChecked(false);
        classThreeButton = new QRadioButton(centralWidget);
        classThreeButton->setObjectName(QString::fromUtf8("classThreeButton"));
        classThreeButton->setGeometry(QRect(730, 760, 16, 17));
        classThreeButton->setChecked(false);
        classOneButton = new QRadioButton(centralWidget);
        classOneButton->setObjectName(QString::fromUtf8("classOneButton"));
        classOneButton->setGeometry(QRect(620, 760, 16, 17));
        classOneButton->setChecked(true);
        classTwoButton = new QRadioButton(centralWidget);
        classTwoButton->setObjectName(QString::fromUtf8("classTwoButton"));
        classTwoButton->setGeometry(QRect(620, 790, 16, 17));
        classTwoButton->setChecked(false);
        pushButton_Capture = new QPushButton(centralWidget);
        pushButton_Capture->setObjectName(QString::fromUtf8("pushButton_Capture"));
        pushButton_Capture->setEnabled(true);
        pushButton_Capture->setGeometry(QRect(10, 360, 61, 31));
        pushButton_SaveClassifier = new QPushButton(centralWidget);
        pushButton_SaveClassifier->setObjectName(QString::fromUtf8("pushButton_SaveClassifier"));
        pushButton_SaveClassifier->setEnabled(true);
        pushButton_SaveClassifier->setGeometry(QRect(490, 750, 91, 31));
        pushButton_LoadClassifer = new QPushButton(centralWidget);
        pushButton_LoadClassifer->setObjectName(QString::fromUtf8("pushButton_LoadClassifer"));
        pushButton_LoadClassifer->setEnabled(true);
        pushButton_LoadClassifer->setGeometry(QRect(280, 750, 91, 31));
        pushButton_StillImage = new QPushButton(centralWidget);
        pushButton_StillImage->setObjectName(QString::fromUtf8("pushButton_StillImage"));
        pushButton_StillImage->setEnabled(true);
        pushButton_StillImage->setGeometry(QRect(220, 360, 101, 31));
        pushButton_TrainClassifer = new QPushButton(centralWidget);
        pushButton_TrainClassifer->setObjectName(QString::fromUtf8("pushButton_TrainClassifer"));
        pushButton_TrainClassifer->setGeometry(QRect(990, 770, 61, 31));
        pushButton_Classify = new QPushButton(centralWidget);
        pushButton_Classify->setObjectName(QString::fromUtf8("pushButton_Classify"));
        pushButton_Classify->setGeometry(QRect(1680, 770, 61, 31));
        classFiveButton = new QRadioButton(centralWidget);
        classFiveButton->setObjectName(QString::fromUtf8("classFiveButton"));
        classFiveButton->setGeometry(QRect(840, 760, 16, 17));
        classFiveButton->setChecked(false);
        classSixButton = new QRadioButton(centralWidget);
        classSixButton->setObjectName(QString::fromUtf8("classSixButton"));
        classSixButton->setGeometry(QRect(840, 790, 16, 17));
        classSixButton->setChecked(false);
        pushButton_ResetBackground = new QPushButton(centralWidget);
        pushButton_ResetBackground->setObjectName(QString::fromUtf8("pushButton_ResetBackground"));
        pushButton_ResetBackground->setEnabled(true);
        pushButton_ResetBackground->setGeometry(QRect(500, 360, 61, 31));
        label_TrainingData = new QLabel(centralWidget);
        label_TrainingData->setObjectName(QString::fromUtf8("label_TrainingData"));
        label_TrainingData->setGeometry(QRect(10, 820, 71, 16));
        label_TrainingClass = new QLabel(centralWidget);
        label_TrainingClass->setObjectName(QString::fromUtf8("label_TrainingClass"));
        label_TrainingClass->setGeometry(QRect(60, 836, 46, 13));
        label_AmountSelected = new QLabel(centralWidget);
        label_AmountSelected->setObjectName(QString::fromUtf8("label_AmountSelected"));
        label_AmountSelected->setGeometry(QRect(122, 826, 51, 31));
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QString::fromUtf8("line_23"));
        line_23->setGeometry(QRect(60, 856, 118, 3));
        line_23->setFrameShape(QFrame::HLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QString::fromUtf8("line_24"));
        line_24->setGeometry(QRect(101, 856, 20, 111));
        line_24->setFrameShape(QFrame::VLine);
        line_24->setFrameShadow(QFrame::Sunken);
        label_ClassifiedData = new QLabel(centralWidget);
        label_ClassifiedData->setObjectName(QString::fromUtf8("label_ClassifiedData"));
        label_ClassifiedData->setGeometry(QRect(240, 820, 71, 16));
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QString::fromUtf8("line_25"));
        line_25->setGeometry(QRect(300, 850, 211, 16));
        line_25->setFrameShape(QFrame::HLine);
        line_25->setFrameShadow(QFrame::Sunken);
        label_AmountClassified = new QLabel(centralWidget);
        label_AmountClassified->setObjectName(QString::fromUtf8("label_AmountClassified"));
        label_AmountClassified->setGeometry(QRect(364, 827, 51, 31));
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QString::fromUtf8("line_26"));
        line_26->setGeometry(QRect(341, 857, 20, 111));
        line_26->setFrameShape(QFrame::VLine);
        line_26->setFrameShadow(QFrame::Sunken);
        label_ClassifiedClass = new QLabel(centralWidget);
        label_ClassifiedClass->setObjectName(QString::fromUtf8("label_ClassifiedClass"));
        label_ClassifiedClass->setGeometry(QRect(300, 837, 46, 13));
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QString::fromUtf8("line_27"));
        line_27->setGeometry(QRect(410, 857, 20, 111));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        label_ClassifiedPercentage = new QLabel(centralWidget);
        label_ClassifiedPercentage->setObjectName(QString::fromUtf8("label_ClassifiedPercentage"));
        label_ClassifiedPercentage->setGeometry(QRect(450, 838, 61, 16));
        overlayWidget_Minioverlay = new CvOverlayWidget(centralWidget);
        overlayWidget_Minioverlay->setObjectName(QString::fromUtf8("overlayWidget_Minioverlay"));
        overlayWidget_Minioverlay->setGeometry(QRect(10, 420, 576, 324));
        pushButton_Previous = new QPushButton(centralWidget);
        pushButton_Previous->setObjectName(QString::fromUtf8("pushButton_Previous"));
        pushButton_Previous->setGeometry(QRect(10, 750, 61, 31));
        pushButton_Next = new QPushButton(centralWidget);
        pushButton_Next->setObjectName(QString::fromUtf8("pushButton_Next"));
        pushButton_Next->setGeometry(QRect(80, 750, 61, 31));
        pushButton_SaveStillImage = new QPushButton(centralWidget);
        pushButton_SaveStillImage->setObjectName(QString::fromUtf8("pushButton_SaveStillImage"));
        pushButton_SaveStillImage->setEnabled(true);
        pushButton_SaveStillImage->setGeometry(QRect(360, 360, 101, 31));
        label_PotatoCount = new QLabel(centralWidget);
        label_PotatoCount->setObjectName(QString::fromUtf8("label_PotatoCount"));
        label_PotatoCount->setGeometry(QRect(1570, 770, 61, 31));
        QFont font;
        font.setPointSize(22);
        font.setBold(true);
        font.setWeight(75);
        label_PotatoCount->setFont(font);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setEnabled(true);
        line_14->setGeometry(QRect(10, 974, 1901, 16));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(510, 820, 20, 161));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(750, 820, 20, 161));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        label_Webcam_2 = new QLabel(centralWidget);
        label_Webcam_2->setObjectName(QString::fromUtf8("label_Webcam_2"));
        label_Webcam_2->setGeometry(QRect(10, 400, 71, 16));
        thresholdSlider = new QSlider(centralWidget);
        thresholdSlider->setObjectName(QString::fromUtf8("thresholdSlider"));
        thresholdSlider->setGeometry(QRect(530, 840, 161, 31));
        thresholdSlider->setMaximum(125);
        thresholdSlider->setValue(40);
        thresholdSlider->setSliderPosition(40);
        thresholdSlider->setOrientation(Qt::Horizontal);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(530, 820, 61, 16));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(530, 880, 61, 16));
        horizontalSlider = new QSlider(centralWidget);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(530, 900, 161, 31));
        horizontalSlider->setMinimum(500);
        horizontalSlider->setMaximum(15500);
        horizontalSlider->setSliderPosition(7000);
        horizontalSlider->setOrientation(Qt::Horizontal);
        label_ThresholdValue = new QLabel(centralWidget);
        label_ThresholdValue->setObjectName(QString::fromUtf8("label_ThresholdValue"));
        label_ThresholdValue->setGeometry(QRect(707, 850, 21, 16));
        label_AreaValue = new QLabel(centralWidget);
        label_AreaValue->setObjectName(QString::fromUtf8("label_AreaValue"));
        label_AreaValue->setGeometry(QRect(700, 910, 31, 16));
        hScroll = new QScrollBar(centralWidget);
        hScroll->setObjectName(QString::fromUtf8("hScroll"));
        hScroll->setGeometry(QRect(960, 750, 931, 16));
        hScroll->setOrientation(Qt::Horizontal);
        vScroll = new QScrollBar(centralWidget);
        vScroll->setObjectName(QString::fromUtf8("vScroll"));
        vScroll->setGeometry(QRect(1890, 30, 16, 721));
        vScroll->setOrientation(Qt::Vertical);
        zoomSlider = new QSlider(centralWidget);
        zoomSlider->setObjectName(QString::fromUtf8("zoomSlider"));
        zoomSlider->setGeometry(QRect(1290, 770, 160, 19));
        zoomSlider->setMinimum(-4);
        zoomSlider->setMaximum(4);
        zoomSlider->setOrientation(Qt::Horizontal);
        statusLabel = new QLabel(centralWidget);
        statusLabel->setObjectName(QString::fromUtf8("statusLabel"));
        statusLabel->setGeometry(QRect(1120, 830, 781, 141));
        overlayWidget = new CvOverlayWidget(centralWidget);
        overlayWidget->setObjectName(QString::fromUtf8("overlayWidget"));
        overlayWidget->setGeometry(QRect(610, 30, 1280, 720));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(1220, 770, 51, 21));
        zoomLabel = new QLabel(centralWidget);
        zoomLabel->setObjectName(QString::fromUtf8("zoomLabel"));
        zoomLabel->setGeometry(QRect(1355, 790, 31, 20));
        zoomLabel->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(1290, 780, 41, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial"));
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        label_5->setFont(font1);
        label_5->setScaledContents(false);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(1420, 790, 46, 13));
        label_6->setFont(font1);
        EditClass1 = new QLineEdit(centralWidget);
        EditClass1->setObjectName(QString::fromUtf8("EditClass1"));
        EditClass1->setGeometry(QRect(640, 760, 81, 20));
        EditClass2 = new QLineEdit(centralWidget);
        EditClass2->setObjectName(QString::fromUtf8("EditClass2"));
        EditClass2->setGeometry(QRect(640, 790, 81, 20));
        EditClass3 = new QLineEdit(centralWidget);
        EditClass3->setObjectName(QString::fromUtf8("EditClass3"));
        EditClass3->setGeometry(QRect(750, 760, 81, 20));
        EditClass4 = new QLineEdit(centralWidget);
        EditClass4->setObjectName(QString::fromUtf8("EditClass4"));
        EditClass4->setGeometry(QRect(750, 790, 81, 20));
        EditClass5 = new QLineEdit(centralWidget);
        EditClass5->setObjectName(QString::fromUtf8("EditClass5"));
        EditClass5->setGeometry(QRect(860, 760, 81, 20));
        EditClass6 = new QLineEdit(centralWidget);
        EditClass6->setObjectName(QString::fromUtf8("EditClass6"));
        EditClass6->setGeometry(QRect(860, 790, 81, 20));
        pushButton_Edit = new QPushButton(centralWidget);
        pushButton_Edit->setObjectName(QString::fromUtf8("pushButton_Edit"));
        pushButton_Edit->setGeometry(QRect(160, 750, 61, 31));
        layoutWidget = new QWidget(centralWidget);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(270, 860, 71, 110));
        verticalLayout_3 = new QVBoxLayout(layoutWidget);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        verticalLayout_3->setContentsMargins(0, 0, 0, 0);
        lblClass1_2 = new QLabel(layoutWidget);
        lblClass1_2->setObjectName(QString::fromUtf8("lblClass1_2"));

        verticalLayout_3->addWidget(lblClass1_2);

        lblClass2_2 = new QLabel(layoutWidget);
        lblClass2_2->setObjectName(QString::fromUtf8("lblClass2_2"));

        verticalLayout_3->addWidget(lblClass2_2);

        lblClass3_2 = new QLabel(layoutWidget);
        lblClass3_2->setObjectName(QString::fromUtf8("lblClass3_2"));

        verticalLayout_3->addWidget(lblClass3_2);

        lblClass4_2 = new QLabel(layoutWidget);
        lblClass4_2->setObjectName(QString::fromUtf8("lblClass4_2"));

        verticalLayout_3->addWidget(lblClass4_2);

        lblClass5_2 = new QLabel(layoutWidget);
        lblClass5_2->setObjectName(QString::fromUtf8("lblClass5_2"));

        verticalLayout_3->addWidget(lblClass5_2);

        lblClass6_2 = new QLabel(layoutWidget);
        lblClass6_2->setObjectName(QString::fromUtf8("lblClass6_2"));

        verticalLayout_3->addWidget(lblClass6_2);

        layoutWidget1 = new QWidget(centralWidget);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(120, 860, 51, 110));
        verticalLayout_2 = new QVBoxLayout(layoutWidget1);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        label_SelectedOneVal = new QLabel(layoutWidget1);
        label_SelectedOneVal->setObjectName(QString::fromUtf8("label_SelectedOneVal"));

        verticalLayout_2->addWidget(label_SelectedOneVal);

        label_SelectedTwoVal = new QLabel(layoutWidget1);
        label_SelectedTwoVal->setObjectName(QString::fromUtf8("label_SelectedTwoVal"));

        verticalLayout_2->addWidget(label_SelectedTwoVal);

        label_SelectedThreeVal = new QLabel(layoutWidget1);
        label_SelectedThreeVal->setObjectName(QString::fromUtf8("label_SelectedThreeVal"));

        verticalLayout_2->addWidget(label_SelectedThreeVal);

        label_SelectedFourVal = new QLabel(layoutWidget1);
        label_SelectedFourVal->setObjectName(QString::fromUtf8("label_SelectedFourVal"));

        verticalLayout_2->addWidget(label_SelectedFourVal);

        label_SelectedFiveVal = new QLabel(layoutWidget1);
        label_SelectedFiveVal->setObjectName(QString::fromUtf8("label_SelectedFiveVal"));

        verticalLayout_2->addWidget(label_SelectedFiveVal);

        label_SelectedSixVal = new QLabel(layoutWidget1);
        label_SelectedSixVal->setObjectName(QString::fromUtf8("label_SelectedSixVal"));

        verticalLayout_2->addWidget(label_SelectedSixVal);

        layoutWidget2 = new QWidget(centralWidget);
        layoutWidget2->setObjectName(QString::fromUtf8("layoutWidget2"));
        layoutWidget2->setGeometry(QRect(30, 860, 71, 110));
        verticalLayout = new QVBoxLayout(layoutWidget2);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        lblClass1 = new QLabel(layoutWidget2);
        lblClass1->setObjectName(QString::fromUtf8("lblClass1"));

        verticalLayout->addWidget(lblClass1);

        lblClass2 = new QLabel(layoutWidget2);
        lblClass2->setObjectName(QString::fromUtf8("lblClass2"));

        verticalLayout->addWidget(lblClass2);

        lblClass3 = new QLabel(layoutWidget2);
        lblClass3->setObjectName(QString::fromUtf8("lblClass3"));

        verticalLayout->addWidget(lblClass3);

        lblClass4 = new QLabel(layoutWidget2);
        lblClass4->setObjectName(QString::fromUtf8("lblClass4"));

        verticalLayout->addWidget(lblClass4);

        lblClass5 = new QLabel(layoutWidget2);
        lblClass5->setObjectName(QString::fromUtf8("lblClass5"));

        verticalLayout->addWidget(lblClass5);

        lblClass6 = new QLabel(layoutWidget2);
        lblClass6->setObjectName(QString::fromUtf8("lblClass6"));

        verticalLayout->addWidget(lblClass6);

        layoutWidget3 = new QWidget(centralWidget);
        layoutWidget3->setObjectName(QString::fromUtf8("layoutWidget3"));
        layoutWidget3->setGeometry(QRect(360, 861, 51, 110));
        verticalLayout_4 = new QVBoxLayout(layoutWidget3);
        verticalLayout_4->setObjectName(QString::fromUtf8("verticalLayout_4"));
        verticalLayout_4->setContentsMargins(0, 0, 0, 0);
        label_ClassifiedOneVal = new QLabel(layoutWidget3);
        label_ClassifiedOneVal->setObjectName(QString::fromUtf8("label_ClassifiedOneVal"));

        verticalLayout_4->addWidget(label_ClassifiedOneVal);

        label_ClassifiedTwoVal = new QLabel(layoutWidget3);
        label_ClassifiedTwoVal->setObjectName(QString::fromUtf8("label_ClassifiedTwoVal"));

        verticalLayout_4->addWidget(label_ClassifiedTwoVal);

        label_ClassifiedThreeVal = new QLabel(layoutWidget3);
        label_ClassifiedThreeVal->setObjectName(QString::fromUtf8("label_ClassifiedThreeVal"));

        verticalLayout_4->addWidget(label_ClassifiedThreeVal);

        label_ClassifiedFourVal = new QLabel(layoutWidget3);
        label_ClassifiedFourVal->setObjectName(QString::fromUtf8("label_ClassifiedFourVal"));

        verticalLayout_4->addWidget(label_ClassifiedFourVal);

        label_ClassifiedFiveVal = new QLabel(layoutWidget3);
        label_ClassifiedFiveVal->setObjectName(QString::fromUtf8("label_ClassifiedFiveVal"));

        verticalLayout_4->addWidget(label_ClassifiedFiveVal);

        label_ClassifiedSixVal = new QLabel(layoutWidget3);
        label_ClassifiedSixVal->setObjectName(QString::fromUtf8("label_ClassifiedSixVal"));

        verticalLayout_4->addWidget(label_ClassifiedSixVal);

        layoutWidget4 = new QWidget(centralWidget);
        layoutWidget4->setObjectName(QString::fromUtf8("layoutWidget4"));
        layoutWidget4->setGeometry(QRect(430, 862, 71, 110));
        verticalLayout_5 = new QVBoxLayout(layoutWidget4);
        verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
        verticalLayout_5->setContentsMargins(0, 0, 0, 0);
        label_ClassifiedOnePer = new QLabel(layoutWidget4);
        label_ClassifiedOnePer->setObjectName(QString::fromUtf8("label_ClassifiedOnePer"));

        verticalLayout_5->addWidget(label_ClassifiedOnePer);

        label_ClassifiedTwoPer = new QLabel(layoutWidget4);
        label_ClassifiedTwoPer->setObjectName(QString::fromUtf8("label_ClassifiedTwoPer"));

        verticalLayout_5->addWidget(label_ClassifiedTwoPer);

        label_ClassifiedThreePer = new QLabel(layoutWidget4);
        label_ClassifiedThreePer->setObjectName(QString::fromUtf8("label_ClassifiedThreePer"));

        verticalLayout_5->addWidget(label_ClassifiedThreePer);

        label_ClassifiedFourPer = new QLabel(layoutWidget4);
        label_ClassifiedFourPer->setObjectName(QString::fromUtf8("label_ClassifiedFourPer"));

        verticalLayout_5->addWidget(label_ClassifiedFourPer);

        label_ClassifiedFivePer = new QLabel(layoutWidget4);
        label_ClassifiedFivePer->setObjectName(QString::fromUtf8("label_ClassifiedFivePer"));

        verticalLayout_5->addWidget(label_ClassifiedFivePer);

        label_ClassifiedSixPer = new QLabel(layoutWidget4);
        label_ClassifiedSixPer->setObjectName(QString::fromUtf8("label_ClassifiedSixPer"));

        verticalLayout_5->addWidget(label_ClassifiedSixPer);

        layoutWidget_2 = new QWidget(centralWidget);
        layoutWidget_2->setObjectName(QString::fromUtf8("layoutWidget_2"));
        layoutWidget_2->setGeometry(QRect(10, 860, 16, 110));
        verticalLayout_7 = new QVBoxLayout(layoutWidget_2);
        verticalLayout_7->setObjectName(QString::fromUtf8("verticalLayout_7"));
        verticalLayout_7->setContentsMargins(0, 0, 0, 0);
        lblColClass_1_2 = new QLabel(layoutWidget_2);
        lblColClass_1_2->setObjectName(QString::fromUtf8("lblColClass_1_2"));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(255, 255, 191, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(127, 127, 63, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(170, 170, 84, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_1_2->setPalette(palette);
        lblColClass_1_2->setAutoFillBackground(true);
        lblColClass_1_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_1_2);

        lblColClass_2_2 = new QLabel(layoutWidget_2);
        lblColClass_2_2->setObjectName(QString::fromUtf8("lblColClass_2_2"));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_2_2->setPalette(palette1);
        lblColClass_2_2->setAutoFillBackground(true);
        lblColClass_2_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_2_2);

        lblColClass_3_2 = new QLabel(layoutWidget_2);
        lblColClass_3_2->setObjectName(QString::fromUtf8("lblColClass_3_2"));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_3_2->setPalette(palette2);
        lblColClass_3_2->setAutoFillBackground(true);
        lblColClass_3_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_3_2);

        lblColClass_4_2 = new QLabel(layoutWidget_2);
        lblColClass_4_2->setObjectName(QString::fromUtf8("lblColClass_4_2"));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_4_2->setPalette(palette3);
        lblColClass_4_2->setAutoFillBackground(true);
        lblColClass_4_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_4_2);

        lblColClass_5_2 = new QLabel(layoutWidget_2);
        lblColClass_5_2->setObjectName(QString::fromUtf8("lblColClass_5_2"));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_5_2->setPalette(palette4);
        lblColClass_5_2->setAutoFillBackground(true);
        lblColClass_5_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_5_2);

        lblColClass_6_2 = new QLabel(layoutWidget_2);
        lblColClass_6_2->setObjectName(QString::fromUtf8("lblColClass_6_2"));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_6_2->setPalette(palette5);
        lblColClass_6_2->setAutoFillBackground(true);
        lblColClass_6_2->setFrameShadow(QFrame::Raised);

        verticalLayout_7->addWidget(lblColClass_6_2);

        layoutWidget5 = new QWidget(centralWidget);
        layoutWidget5->setObjectName(QString::fromUtf8("layoutWidget5"));
        layoutWidget5->setGeometry(QRect(250, 860, 16, 110));
        verticalLayout_6 = new QVBoxLayout(layoutWidget5);
        verticalLayout_6->setObjectName(QString::fromUtf8("verticalLayout_6"));
        verticalLayout_6->setContentsMargins(0, 0, 0, 0);
        lblColClass_1 = new QLabel(layoutWidget5);
        lblColClass_1->setObjectName(QString::fromUtf8("lblColClass_1"));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_1->setPalette(palette6);
        lblColClass_1->setAutoFillBackground(true);
        lblColClass_1->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_1);

        lblColClass_2 = new QLabel(layoutWidget5);
        lblColClass_2->setObjectName(QString::fromUtf8("lblColClass_2"));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_2->setPalette(palette7);
        lblColClass_2->setAutoFillBackground(true);
        lblColClass_2->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_2);

        lblColClass_3 = new QLabel(layoutWidget5);
        lblColClass_3->setObjectName(QString::fromUtf8("lblColClass_3"));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_3->setPalette(palette8);
        lblColClass_3->setAutoFillBackground(true);
        lblColClass_3->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_3);

        lblColClass_4 = new QLabel(layoutWidget5);
        lblColClass_4->setObjectName(QString::fromUtf8("lblColClass_4"));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_4->setPalette(palette9);
        lblColClass_4->setAutoFillBackground(true);
        lblColClass_4->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_4);

        lblColClass_5 = new QLabel(layoutWidget5);
        lblColClass_5->setObjectName(QString::fromUtf8("lblColClass_5"));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_5->setPalette(palette10);
        lblColClass_5->setAutoFillBackground(true);
        lblColClass_5->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_5);

        lblColClass_6 = new QLabel(layoutWidget5);
        lblColClass_6->setObjectName(QString::fromUtf8("lblColClass_6"));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        lblColClass_6->setPalette(palette11);
        lblColClass_6->setAutoFillBackground(true);
        lblColClass_6->setFrameShadow(QFrame::Raised);

        verticalLayout_6->addWidget(lblColClass_6);

        chk_LogImgs = new QCheckBox(centralWidget);
        chk_LogImgs->setObjectName(QString::fromUtf8("chk_LogImgs"));
        chk_LogImgs->setGeometry(QRect(770, 880, 81, 17));
        chk_LogImgs->setChecked(true);
        txtLogPrefix = new QLineEdit(centralWidget);
        txtLogPrefix->setObjectName(QString::fromUtf8("txtLogPrefix"));
        txtLogPrefix->setGeometry(QRect(770, 850, 113, 20));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(770, 830, 51, 16));
        txtLogFolder = new QLineEdit(centralWidget);
        txtLogFolder->setObjectName(QString::fromUtf8("txtLogFolder"));
        txtLogFolder->setGeometry(QRect(910, 850, 121, 20));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(910, 830, 51, 16));
        btnLogFolder = new QPushButton(centralWidget);
        btnLogFolder->setObjectName(QString::fromUtf8("btnLogFolder"));
        btnLogFolder->setGeometry(QRect(1040, 850, 21, 23));
        btnLog = new QPushButton(centralWidget);
        btnLog->setObjectName(QString::fromUtf8("btnLog"));
        btnLog->setGeometry(QRect(970, 920, 91, 41));
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(1080, 820, 20, 161));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        btnOpenFolder = new QPushButton(centralWidget);
        btnOpenFolder->setObjectName(QString::fromUtf8("btnOpenFolder"));
        btnOpenFolder->setGeometry(QRect(770, 920, 75, 23));
        txtLogDesc = new QLineEdit(centralWidget);
        txtLogDesc->setObjectName(QString::fromUtf8("txtLogDesc"));
        txtLogDesc->setGeometry(QRect(910, 880, 151, 20));
        pushButton_TrainClassifer_2 = new QPushButton(centralWidget);
        pushButton_TrainClassifer_2->setObjectName(QString::fromUtf8("pushButton_TrainClassifer_2"));
        pushButton_TrainClassifer_2->setGeometry(QRect(380, 750, 101, 31));
        webcamUI->setCentralWidget(centralWidget);
        statusbar = new QStatusBar(webcamUI);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        webcamUI->setStatusBar(statusbar);

        retranslateUi(webcamUI);
        QObject::connect(pushButton_Capture, SIGNAL(clicked()), webcamUI, SLOT(captureAction()));
        QObject::connect(classOneButton, SIGNAL(clicked()), webcamUI, SLOT(class1Action()));
        QObject::connect(classTwoButton, SIGNAL(clicked()), webcamUI, SLOT(class2Action()));
        QObject::connect(classThreeButton, SIGNAL(clicked()), webcamUI, SLOT(class3Action()));
        QObject::connect(classFourButton, SIGNAL(clicked()), webcamUI, SLOT(class4Action()));
        QObject::connect(classFiveButton, SIGNAL(clicked()), webcamUI, SLOT(class5Action()));
        QObject::connect(classSixButton, SIGNAL(clicked()), webcamUI, SLOT(class6Action()));
        QObject::connect(pushButton_TrainClassifer, SIGNAL(clicked()), webcamUI, SLOT(trainAction()));
        QObject::connect(pushButton_Classify, SIGNAL(clicked()), webcamUI, SLOT(classifyAction()));
        QObject::connect(pushButton_ResetBackground, SIGNAL(clicked()), webcamUI, SLOT(Reset()));
        QObject::connect(pushButton_Previous, SIGNAL(clicked()), webcamUI, SLOT(previousAction()));
        QObject::connect(pushButton_Next, SIGNAL(clicked()), webcamUI, SLOT(nextAction()));
        QObject::connect(pushButton_SaveStillImage, SIGNAL(clicked()), webcamUI, SLOT(saveAction()));
        QObject::connect(pushButton_SaveClassifier, SIGNAL(clicked()), webcamUI, SLOT(saveData()));
        QObject::connect(pushButton_LoadClassifer, SIGNAL(clicked()), webcamUI, SLOT(loadData()));
        QObject::connect(pushButton_StillImage, SIGNAL(clicked()), webcamUI, SLOT(loadImage()));
        QObject::connect(thresholdSlider, SIGNAL(valueChanged(int)), webcamUI, SLOT(updateThreshold(int)));
        QObject::connect(horizontalSlider, SIGNAL(valueChanged(int)), webcamUI, SLOT(updateArea(int)));
        QObject::connect(pushButton_TrainClassifer_2, SIGNAL(clicked()), webcamUI, SLOT(trainAllAction()));

        QMetaObject::connectSlotsByName(webcamUI);
    } // setupUi

    void retranslateUi(QMainWindow *webcamUI)
    {
        webcamUI->setWindowTitle(QApplication::translate("webcamUI", "MainWindow", 0, QApplication::UnicodeUTF8));
        actionWtf->setText(QApplication::translate("webcamUI", "Reload", 0, QApplication::UnicodeUTF8));
        actionPreload->setText(QApplication::translate("webcamUI", "Preload", 0, QApplication::UnicodeUTF8));
        actionPrint->setText(QApplication::translate("webcamUI", "Print", 0, QApplication::UnicodeUTF8));
        actionEmail->setText(QApplication::translate("webcamUI", "Email", 0, QApplication::UnicodeUTF8));
        groundTruth->setText(QApplication::translate("webcamUI", "Ground Truth Script", 0, QApplication::UnicodeUTF8));
        label_Webcam->setText(QApplication::translate("webcamUI", "Webcam Feed", 0, QApplication::UnicodeUTF8));
        label_Interactive->setText(QApplication::translate("webcamUI", "Interactive Overlay", 0, QApplication::UnicodeUTF8));
        classFourButton->setText(QApplication::translate("webcamUI", "Class 4", 0, QApplication::UnicodeUTF8));
        classThreeButton->setText(QApplication::translate("webcamUI", "Class 3", 0, QApplication::UnicodeUTF8));
        classOneButton->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        classTwoButton->setText(QApplication::translate("webcamUI", "Class 2", 0, QApplication::UnicodeUTF8));
        pushButton_Capture->setText(QApplication::translate("webcamUI", "Capture", 0, QApplication::UnicodeUTF8));
        pushButton_SaveClassifier->setText(QApplication::translate("webcamUI", "Save Classifier", 0, QApplication::UnicodeUTF8));
        pushButton_LoadClassifer->setText(QApplication::translate("webcamUI", "Load Classifier", 0, QApplication::UnicodeUTF8));
        pushButton_StillImage->setText(QApplication::translate("webcamUI", "Load Still Image", 0, QApplication::UnicodeUTF8));
        pushButton_TrainClassifer->setText(QApplication::translate("webcamUI", "Train", 0, QApplication::UnicodeUTF8));
        pushButton_Classify->setText(QApplication::translate("webcamUI", "Assess", 0, QApplication::UnicodeUTF8));
        classFiveButton->setText(QApplication::translate("webcamUI", "Class 5", 0, QApplication::UnicodeUTF8));
        classSixButton->setText(QApplication::translate("webcamUI", "Class 6", 0, QApplication::UnicodeUTF8));
        pushButton_ResetBackground->setText(QApplication::translate("webcamUI", "Reset", 0, QApplication::UnicodeUTF8));
        label_TrainingData->setText(QApplication::translate("webcamUI", "Training Data", 0, QApplication::UnicodeUTF8));
        label_TrainingClass->setText(QApplication::translate("webcamUI", "Class", 0, QApplication::UnicodeUTF8));
        label_AmountSelected->setText(QApplication::translate("webcamUI", "Amount\n"
"Selected", 0, QApplication::UnicodeUTF8));
        label_ClassifiedData->setText(QApplication::translate("webcamUI", "Classified Data", 0, QApplication::UnicodeUTF8));
        label_AmountClassified->setText(QApplication::translate("webcamUI", "Amount\n"
"Classified", 0, QApplication::UnicodeUTF8));
        label_ClassifiedClass->setText(QApplication::translate("webcamUI", "Class", 0, QApplication::UnicodeUTF8));
        label_ClassifiedPercentage->setText(QApplication::translate("webcamUI", "Percentage", 0, QApplication::UnicodeUTF8));
        pushButton_Previous->setText(QApplication::translate("webcamUI", "Previous", 0, QApplication::UnicodeUTF8));
        pushButton_Next->setText(QApplication::translate("webcamUI", "Next", 0, QApplication::UnicodeUTF8));
        pushButton_SaveStillImage->setText(QApplication::translate("webcamUI", "Save Still Image", 0, QApplication::UnicodeUTF8));
        label_PotatoCount->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_Webcam_2->setText(QApplication::translate("webcamUI", "Minioverlay", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("webcamUI", "Threshold", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("webcamUI", "Area", 0, QApplication::UnicodeUTF8));
        label_ThresholdValue->setText(QApplication::translate("webcamUI", "40", 0, QApplication::UnicodeUTF8));
        label_AreaValue->setText(QApplication::translate("webcamUI", "7000", 0, QApplication::UnicodeUTF8));
        statusLabel->setText(QString());
        label_3->setText(QApplication::translate("webcamUI", "Zoom", 0, QApplication::UnicodeUTF8));
        zoomLabel->setText(QApplication::translate("webcamUI", "100%", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("webcamUI", "-", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("webcamUI", "+", 0, QApplication::UnicodeUTF8));
        EditClass1->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        EditClass2->setText(QApplication::translate("webcamUI", "Class 2", 0, QApplication::UnicodeUTF8));
        EditClass3->setText(QApplication::translate("webcamUI", "Class 3", 0, QApplication::UnicodeUTF8));
        EditClass4->setText(QApplication::translate("webcamUI", "Class 4", 0, QApplication::UnicodeUTF8));
        EditClass5->setText(QApplication::translate("webcamUI", "Class 5", 0, QApplication::UnicodeUTF8));
        EditClass6->setText(QApplication::translate("webcamUI", "Class 6", 0, QApplication::UnicodeUTF8));
        pushButton_Edit->setText(QApplication::translate("webcamUI", "Edit", 0, QApplication::UnicodeUTF8));
        lblClass1_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass2_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass3_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass4_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass5_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass6_2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        label_SelectedOneVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_SelectedTwoVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_SelectedThreeVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_SelectedFourVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_SelectedFiveVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_SelectedSixVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        lblClass1->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass2->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass3->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass4->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass5->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        lblClass6->setText(QApplication::translate("webcamUI", "Class 1", 0, QApplication::UnicodeUTF8));
        label_ClassifiedOneVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedTwoVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedThreeVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedFourVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedFiveVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedSixVal->setText(QApplication::translate("webcamUI", "0", 0, QApplication::UnicodeUTF8));
        label_ClassifiedOnePer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        label_ClassifiedTwoPer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        label_ClassifiedThreePer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        label_ClassifiedFourPer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        label_ClassifiedFivePer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        label_ClassifiedSixPer->setText(QApplication::translate("webcamUI", "0%", 0, QApplication::UnicodeUTF8));
        lblColClass_1_2->setText(QString());
        lblColClass_2_2->setText(QString());
        lblColClass_3_2->setText(QString());
        lblColClass_4_2->setText(QString());
        lblColClass_5_2->setText(QString());
        lblColClass_6_2->setText(QString());
        lblColClass_1->setText(QString());
        lblColClass_2->setText(QString());
        lblColClass_3->setText(QString());
        lblColClass_4->setText(QString());
        lblColClass_5->setText(QString());
        lblColClass_6->setText(QString());
        chk_LogImgs->setText(QApplication::translate("webcamUI", "Log Images", 0, QApplication::UnicodeUTF8));
        txtLogPrefix->setText(QApplication::translate("webcamUI", "Log", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("webcamUI", "Log prefix:", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("webcamUI", "Log folder:", 0, QApplication::UnicodeUTF8));
        btnLogFolder->setText(QApplication::translate("webcamUI", "...", 0, QApplication::UnicodeUTF8));
        btnLog->setText(QApplication::translate("webcamUI", "Start Logging", 0, QApplication::UnicodeUTF8));
        btnOpenFolder->setText(QApplication::translate("webcamUI", "Open folder", 0, QApplication::UnicodeUTF8));
        txtLogDesc->setText(QApplication::translate("webcamUI", "Optional brief description", 0, QApplication::UnicodeUTF8));
        pushButton_TrainClassifer_2->setText(QApplication::translate("webcamUI", "Train Loaded Data", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class webcamUI: public Ui_webcamUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WEBCAMUI_H
